#!/bin/sh

# needed for handling non-ascii characters in cygwin
LANG=C
LC_CTYPE=C
export LC_CTYPE

ngram-count -debug 1 -text gb.test.txt -lm - \
	-wbdiscount1 -wbdiscount2 -wbdiscount3 | \
make-ngram-pfsg | \
add-pauses-to-pfsg 


