.\" $Id: TEMPLATE.5,v 1.2 2007/12/19 22:08:05 stolcke Exp $
.TH XXX 5 "$Date: 2007/12/19 22:08:05 $" "SRILM File Formats"
.SH NAME
XXX \- XXX
.SH SYNOPSIS
.nf
.B XXX
.fi
.SH DESCRIPTION
.SH "SEE ALSO"
.SH BUGS
.SH "AUTHOR (of this page)"
Andreas Stolcke <stolcke@speech.sri.com>.
.br
Copyright 1999 SRI International
