#!/usr/bin/env perl

@filters=('<SPOKEN_NOISE>','<UNK>');

foreach $w (@filters) {
  $bad{$w} = 1;
}

while(<STDIN>) {
  @A  = split(" ", $_);
  $id = shift @A;
  print "$id ";
  foreach $a (@A) {
    if (!defined $bad{$a}) {
      print "$a ";
    }
  }
  print "\n";
}
