#!/bin/sh
# $Id: do-lm,v 1.3 1996/08/23 22:43:23 robertm Rel $
Usage()
{
cat << EOM 1>&2
Usage: $0 file(s)
  Runs LM pipeline on FILES, with output to "lm" subdirectory of cwd.
  Expects to find LM conditioning tools in PATH or ./bin.
EOM
}

# Excludes "fixvp" stage which has the main effect of killing off
# any SGML tagging that contains a space, e.g. <p id=...>.

# BBN used -np switch for puncproc, removing punctuation; this chooses the
# "verbalize" option instead.

# Includes new "numhack" module to deal with zip codes and phone numbers.

if [ $# -eq 0 ] || [ $1 = "-h" ]; then
	Usage
	exit 1
fi

dir=$1
shift

for file in $*
do
	BASENM=`basename $file`
  name="${BASENM%.*}"

	echo "Running LM pipeline for |$BASENM|..." 1>&2
	set -x
  gunzip -c $file | pare-sgml.perl | \
    bugproc.perl | \
    numhack.perl | \
    numproc.perl -xlocal/data_prep/csr_hub4_utils/num_excp | \
    abbrproc.perl local/data_prep/csr_hub4_utils/abbrlist | \
    puncproc.perl -np | gzip -c > $dir/$name.txt.gz
	set +x
	echo "Done with $BASENM."
done
