.\" $Id: TEMPLATE.3,v 1.4 2007/12/19 22:01:46 stolcke Exp $
.TH XXX 3 "$Date: 2007/12/19 22:01:46 $" SRILM
.SH NAME
XXX \- XXX
.SH SYNOPSIS
.nf
.B #include <XXX.h>
.fi
.SH DESCRIPTION
.SH TYPES
.SH CONSTANTS
.SH FUNCTIONS
.SH "SEE ALSO"
.SH BUGS
.SH AUTHOR
Andreas Stolcke <stolcke@speech.sri.com>.
.br
Copyright 1999 SRI International
