function vOrder = label_reorder_arpabet(PUnsorted)
% Takes an unsorted Phoneme label vector (CMUdict/ARPABET) and brings it 
% into reasonable order, when applied to the unsorted vector, i.e., 
% PUnsorted(vOrder) == CLASSES_ARBABET
% 
% Example: PUnsorted = {'SIL', 'SPN', 'NSN', 'S', 'UW', 'T', 'N', 'K', 'Y', 'Z', 'AO', 'AY', 'SH', 'W', 'NG', 'EY', 'B', 'CH', 'OY', 'JH', 'D', 'ZH', 'G', 'UH', 'F', 'V', 'ER', 'AA', 'IH', 'M', 'DH', 'L', 'AH', 'P', 'OW', 'AW', 'HH', 'AE', 'R', 'TH', 'IY', 'EH'};
% vOrder = label_reorder_arpabet(PUnsorted);
% PUnsorted(vOrder)
% Bernd T Meyer, JHU
CLASSES_ARPABET = {'AO','AA','IY','UW','EH','IH','UH','AH','AE','EY','AY','OW','AW','OY','ER','P','B','T','D','K','G','CH','JH','F','V','TH','DH','S','Z','SH','ZH','HH','M','N','NG','L','R','Y','W','NSN','SIL','SPN'};
vOrder = zeros(1,length(CLASSES_ARPABET));

% Find the classes with something like this: 
% index = find(ismember(CLASSES_ARPABET, PUnsorted{1}))
for k=1:length(CLASSES_ARPABET)
  vOrder(k) = find(ismember(PUnsorted, CLASSES_ARPABET{k}));
end
% Sanity check
if ~isequal(unique(vOrder),1:length(PUnsorted))
  error('This should not happen, check your phonemes.')
end
return


% % Proper order, see https://en.wikipedia.org/wiki/Arpabet
% % and the according Excel spreadsheet that I made
% CLASSES = {'AO','MONOPHTHONG','VOWEL'; ...
%   'AA','MONOPHTHONG','VOWEL'; ...
%   'IY','MONOPHTHONG','VOWEL'; ...
%   'UW','MONOPHTHONG','VOWEL'; ...
%   'EH','MONOPHTHONG','VOWEL'; ...
%   'IH','MONOPHTHONG','VOWEL'; ...
%   'UH','MONOPHTHONG','VOWEL'; ...
%   'AH','MONOPHTHONG','VOWEL'; ...
%   'AE','MONOPHTHONG','VOWEL'; ...
%   'EY','DIPHTHONG','VOWEL'; ...
%   'AY','DIPHTHONG','VOWEL'; ...
%   'OW','DIPHTHONG','VOWEL'; ...
%   'AW','DIPHTHONG','VOWEL'; ...
%   'OY','DIPHTHONG','VOWEL'; ...
%   'ER','R-COLORED-VOWEL','VOWEL'; ...
%   'P','STOP','CONSONANT'; ...
%   'B','STOP','CONSONANT'; ...
%   'T','STOP','CONSONANT'; ...
%   'D','STOP','CONSONANT'; ...
%   'K','STOP','CONSONANT'; ...
%   'G','STOP','CONSONANT'; ...
%   'CH','AFFRICATIVE','CONSONANT'; ...
%   'JH','AFFRICATIVE','CONSONANT'; ...
%   'F','FRICATIVE','CONSONANT'; ...
%   'V','FRICATIVE','CONSONANT'; ...
%   'TH','FRICATIVE','CONSONANT'; ...
%   'DH','FRICATIVE','CONSONANT'; ...
%   'S','FRICATIVE','CONSONANT'; ...
%   'Z','FRICATIVE','CONSONANT'; ...
%   'SH','FRICATIVE','CONSONANT'; ...
%   'ZH','FRICATIVE','CONSONANT'; ...
%   'HH','FRICATIVE','CONSONANT'; ...
%   'M','NASAL','CONSONANT'; ...
%   'N','NASAL','CONSONANT'; ...
%   'NG','NASAL','CONSONANT'; ...
%   'L','LIQUID','CONSONANT'; ...
%   'R','LIQUID','CONSONANT'; ...
%   'Y','SEMIVOWEL','CONSONANT'; ...
%   'W','SEMIVOWEL','CONSONANT'; ...
%   'NSN','NONSPEECHNOISE','OTHER'; ...
%   'SIL','SILENCE','OTHER'; ...
%   'SPN','SPEECHNOISE','OTHER'};