
all:

include ../kaldi.mk


TESTFILES = boolean-io-funcs-test

OBJFILES = tree-stats.o 

LIBNAME = kaldi-decision-tree
ADDLIBS = ../util/kaldi-util.a ../matrix/kaldi-matrix.a ../base/kaldi-base.a


include ../makefiles/default_rules.mk

