#!/usr/bin/env python

# script to parse the train logs generated by nnet-compute-prob
from __future__ import division
import sys, glob, re, numpy, math, datetime, argparse
from subprocess import Popen, PIPE

def Main():
    parser = argparse.ArgumentParser(description="Prints accuracy/log-probability across iterations")
    parser.add_argument("--key", type=str, default="accuracy",
                       help="Value to print out")
    parser.add_argument("exp_dir", help="experiment directory, e.g. exp/nnet3/tdnn")

    args = parser.parse_args()
    exp_dir = args.exp_dir
    [report, times, data] = GenerateAccuracyReport(exp_dir, args.key)
    print report

if __name__ == "__main__":
    Main() 


if __name__ == "__main__":
  parser = argparse.ArgumentParser(description="Prints accuracy/log-probability across iterations")
  parser.add_argument("--key", type=str, default="relative-difference",
                       help="Value to print out", choices = ["relative-difference", 'difference'])
  parser.add_argument("exp_dir", help="experiment directory, e.g. exp/nnet3/tdnn")

  args = parser.parse_args()
  exp_dir = args.exp_dir
  if args.key == "relative-difference":
      key = "Relative parameter differences"
  else:
      key = "Parameter differences"
  data = ParseLogsForParamDiff(exp_dir, key)
  for row in data:
      print " ".join(map(lambda x:str(x),row))
