#!/bin/sh

if [ -f ../ngram-count-gt/swbd.3bo.gz ]; then
	gz=.gz
else
	gz=
fi

# restrict LM to small test set vocabulary
head -2 ../ngram-count-gt/eval97.text | \
ngram-count -text - -write-vocab eval97.vocab

ngram -lm ../ngram-count-gt/swbd.3bo$gz -vocab eval97.vocab \
	-limit-vocab -write-lm swbd-eval97-vocab.3bo$gz

ngram -debug 1 \
	-lm ../ngram-count-gt/swbd.3bo$gz -lambda 0.3 \
	-mix-lm ../class-ngram-simple/train-400classes.3bo$gz \
	-classes ../class-ngram-simple/train+unk.400classes$gz \
	-simple-classes \
	-mix-lm2 ../ngram-count-gt/swbd.3bo$gz -mix-lambda2 0.3 \
	-loglinear-mix \
	-rescore-ngram swbd-eval97-vocab.3bo$gz \
	-write-lm logmix.3bo$gz

head -2 ../ngram-count-gt/eval97.text | \
ngram -debug 1 \
	-lm logmix.3bo$gz -ppl -

rm -f eval97.vocab swbd-eval97-vocab.3bo$gz logmix.3bo$gz

