#!/usr/bin/env bash

tmp_dir=data/local/tmp
train_all=data/train_all

if [ $# -lt 1 ]; then
    echo "Specify the location of the split files"
    exit 1;
fi

splitFile=$1
split=train
# Train only
if [ -d $tmp_dir/$split ]; then
    rm -r $tmp_dir/$split
fi
cp -r $train_all $tmp_dir/$split

awk 'BEGIN {FS=" "}; FNR==NR { a[$1]; next } ((substr($2,0,length($2)-2) ".sph") in a)' \
$splitFile/$split $train_all/segments > $tmp_dir/$split/segments

n=`awk 'BEGIN {FS = " "}; {print substr($2,0,length($2)-2)}' $tmp_dir/$split/segments | sort | uniq | wc -l`

echo "$n conversations left in split $split"

utils/fix_data_dir.sh $tmp_dir/$split
utils/validate_data_dir.sh $tmp_dir/$split
rm $tmp_dir/$split/*.tmp

