#!/bin/sh
#    File:   make-standard-directories
#    Author: The SRI DECIPHER (TM) System
#    Date:   Wed Nov  4 00:36:38 1992
#
#    Description:
#	This script makes the standard directories for a submodule
#	of the DECIPHER (TM) system.
#
#    Copyright (c) 1992-2011 SRI International.  All Rights Reserved.
#
#    RCS ID: $Id: make-standard-directories,v 1.3 2011/10/21 21:25:58 stolcke Exp $
#

# If necessary, make the documentation directory.
[ -d doc ] || mkdir doc

# If necessary, make the source code directory.
[ -d src ] || mkdir src

# If necessary, make the object code directory.
[ -d obj ] || mkdir obj

# If necessary, make the binary code directory.
[ -d bin ] || mkdir bin

