.\" $Id: TEMPLATE.1,v 1.4 2007/12/20 19:13:52 stolcke Exp $
.TH XXX 1 "$Date: 2007/12/20 19:13:52 $" "SRILM Tools"
.SH NAME
XXX \- XXX
.SH SYNOPSIS
.nf
.B XXX
.fi
.SH DESCRIPTION
.SH OPTIONS
.SH "SEE ALSO"
.SH BUGS
.SH AUTHOR
Andreas Stolcke <stolcke@speech.sri.com>.
.br
Copyright 1999 SRI International
