.\" $Id: TEMPLATE.7,v 1.1 2007/12/20 19:28:10 stolcke Exp $
.TH XXX 7 "$Date: 2007/12/20 19:28:10 $" "SRILM Miscellaneous"
.SH NAME
XXX \- XXX
.SH SYNOPSIS
.nf
.B XXX
.fi
.SH DESCRIPTION
.SH "SEE ALSO"
.SH BUGS
.SH AUTHOR
Andreas Stolcke <stolcke@speech.sri.com>
.br
Copyright 2007 SRI International
