#!/bin/sh

if [ -f ch_lm_train100.noamp.decomposed.txt.gz ]; then
	gz=.gz
else
	gz=
	sed 's,\.gz,,g' test.flm > test.flm.nogz && \
	mv test.flm test.flm-gz && \
	mv test.flm.nogz test.flm
fi

fngram-count -debug 2 -factor-file test.flm -text ch_lm_train100.noamp.decomposed.txt$gz -write-counts -lm -unk -nonull

fngram -debug 0 -factor-file test.flm -ppl ch_lm_dev.noamp.decomposed.txt$gz -unk -nonull

rm -f dev.count$gz dev.lm$gz

if [ -f test.flm-gz ]; then
	mv test.flm-gz test.flm
fi

