
## static, no cuda, openblas
## for further dynamic linking based on kaldi.
## openfst and kaldi compiled with -fPIC by modifying ../tools/Makefile and kaldi.mk with "CXXFLAGS += -fPIC".
## kaldi.mk is generated by running ./configure below.
## openblas should be prepared before in ../tools.
#./configure --static \
#            --use-cuda=no \
#            --mathlib=OPENBLAS --openblas-root=../tools/OpenBLAS/install \
#            --threaded-math=no --static-math=yes \
#            --static-fst=yes --fst-root=../tools/openfst


# static, cuda, mkl
# for local model training.
./configure --static \
            --use-cuda=yes --cudatk-dir=/nfs/disk/work/users/zhaomy/cuda/cuda-8.0 \
            --mathlib=MKL \
            --mkl-root=/nfs/disk/perm/tools/intel/parallel_studio_xe_2013/composer_xe_2013_sp1.0.080/mkl \
            --mkl-libdir=/nfs/disk/perm/tools/intel/parallel_studio_xe_2013/composer_xe_2013_sp1.0.080/mkl/lib/intel64 \
            --threaded-math=no --static-math=yes \
            --static-fst=yes --fst-root=../tools/openfst \
            --omp-libdir=/nfs/disk/perm/tools/intel/parallel_studio_xe_2013/composer_xe_2013_sp1.0.080/compiler/lib/intel64

