
# Kaldi compiled with static, cuda and openblas.
# For further dynamic linking based on kaldi (usually no cuda),
# compile openfst and kaldi with -fPIC by modifying
# ../tools/Makefile and kaldi.mk with "CXXFLAGS += -fPIC".
# kaldi.mk is generated by running ./configure below.
# openblas should be prepared before in ../tools.
./configure --static \
            --use-cuda=yes --cudatk-dir=/freeneb/home/zhaomy/cuda/cuda-8.0 \
            --mathlib=OPENBLAS --openblas-root=../tools/OpenBLAS/install \
            --threaded-math=no --static-math=yes \
            --static-fst=yes --fst-root=../tools/openfst

