
CUDA_INCLUDE += -I$(CUDNNROOT)/include
CUDA_FLAGS += -DHAVE_CUDNN
CXXFLAGS += -DHAVE_CUDNN -I$(CUDNNROOT)/include
CUDA_LDFLAGS += -L$(CUDNNROOT)/lib64 -Wl,-rpath,$(CUDNNROOT)/lib64
CUDA_LDLIBS += -lcudnn
