
all:

include ../kaldi.mk

TESTFILES = kaldi-math-test io-funcs-test kaldi-error-test

OBJFILES = kaldi-math.o kaldi-error.o io-funcs.o kaldi-utils.o

LIBNAME = kaldi-base

ADDLIBS =

include ../makefiles/default_rules.mk

