

all:

OPENFST_CXXFLAGS =
OPENFST_LDLIBS =

include ../kaldi.mk


# you can uncomment matrix-lib-speed-test if you want to do the speed tests.

TESTFILES = cblasext-test

OBJFILES = cblas-extensions.o

LIBNAME = kaldi-cblasext

ADDLIBS = ../base/kaldi-base.a

include ../makefiles/default_rules.mk

